spring:
   ## JPA Config
   datasource:
      url: jdbc:mysql://localhost:3306/sofia2_s4c?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
      username: root
      password:  
   jpa:
      ## Hibernate Properties
      # The SQL dialect makes Hibernate generate better SQL for the chosen database
      properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
      # Hibernate ddl auto (create, create-drop, validate, update)
      hibernate.ddl-auto: create
   quartz:
      url: jdbc:mysql://localhost:3306/sofia2_s4c_scheduler?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
      username: root
      password:
      autoStartupSchedulers:
         - scriptScheduler
         #- twitterScheduler
         
            
## LOGGING CONF
logging:
   level:
      org.springframework: debug
      com.example.boot.thymeleaf: debug
      com.indra: debug
      org.hibernate: debug


 