version: "3"

services:  
  zookeeper:
    image: sofia2/zookeeper-secured:4.1.0
    container_name: zookeeper  
    ports:
     - "2181:2181"
    environment:
       ZOOKEEPER_CLIENT_PORT: "2181"
    network_mode: host
  kafka:
    image: sofia2/kafka-secured:4.1.0
    container_name: kafka    
    ports:
     - "9093:9093"
     - "9092:9092" 
    environment:
       KAFKA_ZOOKEEPER_CONNECT: "localhost:2181"
       KAFKA_ADVERTISED_LISTENERS: "SASL_PLAINTEXT://localhost:9093,PLAINTEXT://localhost:9092"
       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
    depends_on:
     - zookeeper      
    network_mode: host
  schema-registry:
    image: confluentinc/cp-schema-registry:latest
    container_name: schema-registry    
    ports:
     - "8081:8081"
    environment:
       SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: "localhost:2181"
       SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "PLAINTEXT://localhost:9092"
       SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL: "PLAINTEXT"
       SCHEMA_REGISTRY_KAFKASTORE_SASL_MECHANISM: "PLAIN"
       SCHEMA_REGISTRY_HOST_NAME: "schema-registry"
       SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:8081"
    depends_on:
     - zookeeper
     - kafka
    network_mode: host
  kafka-rest:
    image: confluentinc/cp-kafka-rest:latest
    container_name: kafka-rest    
    ports:
     - "8082:8082"
    environment:
       KAFKA_REST_ZOOKEEPER_CONNECT: "localhost:2181"
       KAFKA_REST_LISTENERS: "http://0.0.0.0:8082"
       KAFKA_REST_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
       KAFKA_REST_HOST_NAME: "kafka-rest"
    depends_on:
     - zookeeper
     - kafka  
     - schema-registry   
    network_mode: host
