sofia2:
   database.mongodb:
      servers: realtimedb:27017
      quasar.connector.http.endpoint: http://quasar:10800/query/fs/       
   iotbroker.plugbable:
     gateway:
       rest:
         swaggerhost: ${SERVER_NAME}  

spring:
   datasource:  
      url: jdbc:mysql://configdb:3306/sofia2_s4c?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false            
quartz:
    datasource:
      url: jdbc:mysql://schedulerdb:3306/sofia2_s4c_scheduler?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false

## LOGGING CONF
logging:
   path: /var/log/logs-s4c 
   file: ${logging.path}/${app.name}.log
   pattern:
      console: