##--spring.config.name=controlpanel
##security.require_ssl: true
server: ## Config Web Server
   port: 18080
   contextPath: /controlpanel
   tomcat:
      access_log_enabled: true
      basedir: target/tomcat

sofia2: #Config Sofia2 specific
   encription.key: sofia2
   database.mongodb:
      database: sofia2_s4c
      authenticationDatabase:  #admin
      servers: localhost:27017
      autoConnectRetry: true
      socketTimeout: 5000
      maxAutoConnectRetryTime: 5000
      maxWaitTime: 5000
      useAuth: false
      username: #username
      password: #password
      readFromSecondaries: false
      queries.executionTimeout: 5000
      queries.defaultLimit: 50
      queries.maxConcurrentQueries: 3
      writeConcern: UNACKNOWLEDGED
      tools.mongoexport.path: mongoexport
      tools.mongoimport.path: mongoimport
      tools.mongoshell.path: mongo
      tools.useSequentialOps: true
   urls:
    iotbroker: http://localhost:18080
    iotbroker.services: http://localhost:8080/sib/services
   paths:
    ssap: /ssap
    
    
management.security.enabled: false
 
spring: ## General Config  
   application.name: sofia2-control-panel
   thymeleaf: ## Thymeleaf Config
      cache: false  
      encoding: UTF-8
      check-template: true
      check-template-location: true
      content-type: text/html
      enabled: true
      # excluded-view-names:
      # mode: HTML5
      # prefix: /templates/
      # suffix: .html
      # template-resolver-order:
      # view-names:
   datasource: ## JPA Config
      url: jdbc:mysql://localhost:3306/sofia2_s4c?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
      username: root
      password:
      # Number of ms to wait before throwing an exception if no connection is available.
      tomcat.max-wait: 10000
      # Maximum number of active connections that can be allocated from this pool at the same time.
      tomcat.max-active: 50
      # Validate the connection before borrowing it from the pool.
      tomcat.test-on-borrow: true
   jpa:
      ## Hibernate Properties
      # The SQL dialect makes Hibernate generate better SQL for the chosen database
      properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
      # Hibernate ddl auto (create, create-drop, validate, update)
      hibernate.ddl-auto: update
   boot.admin: #Spring Boot Admin Config    
      url: http://localhost:18090
      username: operations
      password: changeIt!
      client.metadata.user.name: ${spring.boot.admin.username}
      client.metadata.user.password: $spring.boot.admin.password} 
      
quartz:      
   datasource:
      url: jdbc:mysql://localhost:3306/sofia2_s4c_scheduler?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
      username: root
      password: 
      driver-class-name: com.mysql.jdbc.Driver
   jpa:
      ## Hibernate Properties
      # The SQL dialect makes Hibernate generate better SQL for the chosen database
      properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
      # Hibernate ddl auto (create, create-drop, validate, update)
      properties.hibernate.hbm2ddl.auto: create
   autoStartupSchedulers:
      #- scriptScheduler
      #- twitterScheduler  
     
      
## LOGGING CONF
logging:
   level:
      org.springframework: INFO
      com.example.boot.thymeleaf: INFO
      com.indra: DEBUG
      org.hibernate: INFO


 
